package schema

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// SimpleGenerator is a minimal Generator implementation that emits a
// small placeholder Go file for the supplied schemas. It is intended as
// a development-time helper so the rest of the toolchain can be exercised
// while a full code generator is built.
//
// The generated file is intentionally small and contains:
//   - a header comment with provenance and timestamp
//   - a short summary of the schema files used
//   - a note describing the recommended commit step after generation
type SimpleGenerator struct {
	// Author is an optional author string included in the generated file.
	Author string
}

// NewSimpleGenerator constructs a SimpleGenerator. The author string may be
// empty.
func NewSimpleGenerator(author string) *SimpleGenerator {
	return &SimpleGenerator{Author: author}
}

// GenerateFromSchemas implements the Generator interface. It writes a single
// placeholder Go file into outDir. If outDir does not exist it will be created.
func (g *SimpleGenerator) GenerateFromSchemas(schemas []*Schema, outDir string) error {
	if outDir == "" {
		return fmt.Errorf("output directory is empty")
	}

	// Ensure output directory exists
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output directory %s: %w", outDir, err)
	}

	// Build a list of schema paths for the header
	var schemaPaths []string
	for _, s := range schemas {
		if s == nil {
			continue
		}
		if s.Path != "" {
			schemaPaths = append(schemaPaths, s.Path)
		}
	}

	// Target file
	outFile := filepath.Join(outDir, "zz_generated_by_exi_go.go")
	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("create generated file %s: %w", outFile, err)
	}
	defer f.Close()

	timestamp := time.Now().UTC().Format(time.RFC3339)
	author := g.Author
	if author == "" {
		author = "exi-go (SimpleGenerator)"
	}

	header := fmt.Sprintf(`// Code generated by exi-go (SimpleGenerator).
// Generated at: %s
// Author: %s
//
// NOTE: This is a placeholder file produced by the simple generator.
// The real generator should emit strongly-typed Go structs and schema-
// informed EXI grammar glue for all parsed XSD constructs.
//
// Source schema files used for generation:
//   %s
//
// Commit step (recommended):
//   The generator has written files into: %s
//   Please review the generated artifacts and then commit them with:
//
//     git add %s
//     git commit -m "gen: add generated types from XSDs (%s)"
//
// Replace the placeholder content with the real generated code as the
// generator is implemented further.
package generated

// This file intentionally contains no functional types. It exists to prove
// the generation pipeline and to provide a safe location for iterative
// development of the full XSD -> Go generator.
`, timestamp, author, strings.Join(schemaPaths, "\n//   "), outDir, outDir, strings.Join(schemaPaths, ", "))

	if _, err := f.WriteString(header); err != nil {
		return fmt.Errorf("write generated file header: %w", err)
	}

	return nil
}

// RunSimpleGeneration is a small helper used by CLI glue to run the simple
// generator end-to-end. It locates XSD files from schemaPaths (files or dirs),
// loads them and runs the SimpleGenerator to emit placeholder code.
//
// This helper is written to be easy to call from a CLI or tests; it does not
// attempt to be comprehensive. Use schema.LoadSchemas and schema.ParseSchemas
// (when implemented) for richer parsing.
func RunSimpleGeneration(schemaPaths []string, outDir string, author string) error {
	if len(schemaPaths) == 0 {
		return fmt.Errorf("no schema paths provided")
	}

	schemas, err := LoadSchemas(schemaPaths)
	if err != nil {
		return fmt.Errorf("loading schemas: %w", err)
	}

	gen := NewSimpleGenerator(author)
	if err := gen.GenerateFromSchemas(schemas, outDir); err != nil {
		return fmt.Errorf("generation failed: %w", err)
	}

	return nil
}
