package schema

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestSimpleGenerationCreatesPlaceholder verifies that the simple generator
// produces a placeholder Go file when given a schema directory.
//
// This test expects community schema files to be available under:
//
//	exi-go/schemas/switchev
//
// If those files are not present on the filesystem, the test will be skipped.
func TestSimpleGenerationCreatesPlaceholder(t *testing.T) {
	// schemaDir is relative to this package directory: exi-go/pkg/schema
	schemaDir := filepath.Join("..", "..", "schemas", "switchev")
	if _, err := os.Stat(schemaDir); os.IsNotExist(err) {
		t.Skipf("schema directory %s not found; skipping test", schemaDir)
	}

	outDir := t.TempDir()

	if err := RunSimpleGeneration([]string{schemaDir}, outDir, "exi-go-test"); err != nil {
		t.Fatalf("RunSimpleGeneration failed: %v", err)
	}

	genFile := filepath.Join(outDir, "zz_generated_by_exi_go.go")
	info, err := os.Stat(genFile)
	if err != nil {
		t.Fatalf("generated file not found: %v", err)
	}
	if info.Size() == 0 {
		t.Fatalf("generated file %s is empty", genFile)
	}

	// Verify the generated file contains the expected header marker.
	data, err := os.ReadFile(genFile)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "Code generated by exi-go") {
		t.Errorf("generated file header does not contain expected marker; header:\n%s", content[:min(len(content), 256)])
	}
}

// min is a small helper used in the test output above.
func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
